[package]
name = "adventofcode-2023"
version = "0.1.0"
edition = "2021"
[dependencies]
phf = { version = "0.11.2", features = ["macros"] }

[[bin]]
name = "es1"
path = "src/bin/es1/es.rs"

[[bin]]
name = "es2"
path = "src/bin/es2/es.rs"

[[bin]]
name = "es3"
path = "src/bin/es3/es.rs"
